name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch: # Allow manual trigger

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in wordpress posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://headingtag.com/rss.xml"
          user_agent: "Mozilla/5.0 (compatible; GitHubActions/1.0)"
